### ISSUE TITLE
[BE] https 요청에 의해 서버가 꺼지는 문제

### ISSUE THREAD

**Issue by violet-mj** [softeerbootcamp4th/Team1-Strawberry-BE#44]
## 어떤 버그인가요?

> ec2에서 spring boot 실행 중 갑자기 shutdown 되는 문제

## 어떤 상황에서 발생한 버그인가요?

// given

// when
spring boot 서버를 켜놓은 상태

// then
```
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x030xb8h0xb820x890xf20xd5D0xda0xef\p0xc7C0x8e}0x1f0xa20x970x94M0xf70x1eV0xe50x86F\0xa00x91P0x14 ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:262)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
        at [org.apache.tomcat.util.net](http://org.apache.tomcat.util.net/).NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
        at [org.apache.tomcat.util.net](http://org.apache.tomcat.util.net/).SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-30T08:13:48.752Z  INFO 11850 --- [backend] [SpringApplicationShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit ‘default’
2024-07-30T08:13:48.759Z  INFO 11850 --- [backend] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-07-30T08:13:51.580Z  INFO 11850 --- [backend] [SpringApplicationShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2024-07-30T08:18:07.680Z  INFO 12246 --- [backend] [main] c.h.softeer.backend.BackendApplication   : Starting BackendApplication v0.0.1-SNAPSHOT using Java 17.0.11 with PID 12246 (/home/ubuntu/backend/application.jar started by ubuntu in /home/ubuntu/backend/scripts)
2024-07-30T08:18:07.687Z  INFO 12246 --- [backend] [main] c.h.softeer.backend.BackendApplication   : The following 1 profile is active: “prod”
```

위 에러가 발생했습니다.

## 예상 결과

> 무중단 서버를 구축할 수 없다.

**Comment by min9805** [comment]
ALB 및 도메인을 통한 Https 적용
